<?xml version="1.0" encoding="utf-8"?>
<Database Name="vips" Class="Linq2SQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DBOBJ" Member="DBOBJs">
    <Type Name="DBOBJ">
      <Column Name="oid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ctime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="last_vnr" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="last_mtime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="moid" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DBVAL" Member="DBVALs">
    <Type Name="DBVAL">
      <Column Name="oid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vnr" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="indx" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="stringValue" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DBVVAL" Member="DBVVALs">
    <Type Name="DBVVAL">
      <Column Name="oid" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vnr" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mtime" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="stat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MOATT" Member="MOATTs">
    <Type Name="MOATT">
      <Column Name="aid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="moid" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="attributeName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TUSR" Member="TUSRs">
    <Type Name="TUSR">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>